name: Push

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/deploy-*.yaml"
      - "!**/README.md"

jobs:
  environment: dev
  ci:
    name: ci
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: build
        uses: actions/setup-node@v2
        with:
          node-version: 10
        run: |
          npm i
          npm run build
        env:
          CI: true

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist

      - name: Deploy to DEV S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'dist'
          TARGET_DIR: '${process.env.GITHUB_RUN_NUMBER}/'

     - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}

      - name: Terragrunt Apply
        working-directory: ${{ env.TG_SRC_PATH }}/${{ env.TFC_WORKSPACE }}
        env:
          app_version: ${{ process.env.GITHUB_RUN_NUMBER }}
          s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
        run: terragrunt apply-all --terragrunt-non-interactive
