name: PR Testing

on: [pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    environment: dev
    strategy:
      matrix:
        node: ['16']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}


      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - run: yarn test-ci
      - name: Cancelling workflow due to error
        if: ${{ failure() }}
        uses: andymckay/cancel-action@0.2
